sudo: true
services:
  - docker

before_install:
  - docker pull ptpadan1246/amazonlinux_ansible
  - docker pull centos:6

script:
  - docker build -f docker/Dockerfile-centos -t centos .
  - docker build -f docker/Dockerfile-amazone -t amazone .

