---

- name: yum clean
  shell: yum clean all

- name: upgrade all packages
  yum: name=* state=latest

- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - make
    - glibc-headers
    - openssl-devel
    - readline
    - libyaml-devel
    - readline-devel
    - sqlite-devel
    - wget
    - expect
    - zip
    - unzip
    - curl
    - bison

- name: ntp install
  yum: name={{ item }} state=latest
  with_items:
    - ntp

- name: ntp start
  service: name=ntpd state=started enabled=yes
